[project]
name = "interactive-data-viz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "geopandas>=1.0.1",
    "pandas>=2.2.3",
    "ruff>=0.8.0",
    "vega-datasets>=0.9.0",
]
